### ISSUE TITLE
No Posts Found error in Content Views

### ISSUE THREAD

**Issue by KilakwaBT** [agileware/content-views-civicrm-data-processor#1]
I am working on trying to get this to work and keep running into an issue where the Content View I create is not finding any posts. I created a simple Data Processor based on the instructions in the Read Me file. The processor works but the Content View plugin cannot seem to pull the data. I feel like I am missing something simple.  A couple questions:
* What should I name the API Entity? Not sure how Content Views finds the entity for data processor.
* The fields for ID & Title. I assume these become the post ID & Posts Title. I am using the Contact ID field for ID and Display Name for title. Is this correct?

I'd like to do some extensive testing with this once I get it running. I think it has a lot of potential.

Thanks

**Comment by agileware-pengyi** [comment]
@KilakwaBT thanks for trying this out. I will do some tests on this later to see if I can find some errors.
For your questions:

- The API name can be any valid CiviCRM API name, like `MemberListing`. Just don't use an existing API name
- You are right. Here is an example (getting from `DataProcessorField` API)
```json
{
            "id": "1",
            "data_processor_id": "1",
            "weight": "1",
            "name": "id",
            "title": "ID",
            "type": "raw",
            "configuration": {
                "field": "id",
                "datasource": "_select_",
                "is_aggregate": ""
            }
        },
        {
            "id": "2",
            "data_processor_id": "1",
            "weight": "2",
            "name": "title",
            "title": "Sort Name",
            "type": "raw",
            "configuration": {
                "field": "sort_name",
                "datasource": "_select_",
                "is_aggregate": ""
            }
        }
}
```

Agileware ref: WPCV-24

**Comment by agileware-pengyi** [comment]
@KilakwaBT could you please try the new version? I have fully tested it and should work now.

**Comment by KilakwaBT** [comment]
I loaded the new version and it attempts to load. Thanks for the dropdown for the data processor! I suspect it has to do with the ID & Title fields I setup. Below is what I get from `DataProcessorField `API. The configuration values are a bit different, but looks like they should work. When I try to preview in Content Views I just get a spinning wheel no results. Let me know if you see anything I am doing wrong. I will keep working on it. Thanks 


```
  {
            "id": "10",
            "data_processor_id": "2",
            "weight": "4",
            "name": "id",
            "title": "ID",
            "type": "raw",
            "configuration": {
                "field": "individual_id",
                "datasource": "individual",
                "is_aggregate": ""
            }
        },
        {
            "id": "11",
            "data_processor_id": "2",
            "weight": "5",
            "name": "title",
            "title": "Title",
            "type": "raw",
            "configuration": {
                "field": "individual_sort_name",
                "datasource": "individual",
                "is_aggregate": ""
            }
```

**Comment by KilakwaBT** [comment]
Got It! I needed to add a filter to my data processor. Getting data now. 

Thanks!!

**Comment by agileware-pengyi** [comment]
That sounds like a bug. I will check it later.
Anyway, thanks for your time @KilakwaBT

**Comment by KilakwaBT** [comment]
I installed Content Views Pro and no longer get results. The drop down to select data processors from CiviCRM is no longer there.

**Comment by jusfreeman** [comment]
@KilakwaBT did you apply the patch to Content Views Pro? If not, give that a go.

**Comment by agileware-pengyi** [comment]
I've pushed the new version 0.1.3.
For this CiviCRM plugin to work with Content Views PRO, the patch is mandatory.
@KilakwaBT please try the new version and apply the patch if you are using PRO.

**Comment by KilakwaBT** [comment]
Got it, loaded newest version and patch. Work fine. Thanks

**Comment by ebenezer-bendov** [comment]
okay found the patch.
