### ISSUE TITLE
Dataprocessor but no data in preview.

### ISSUE THREAD

**Issue by ebenezer-bendov** [agileware/content-views-civicrm-data-processor#7]
Hi Justin

I get the message "
API (MemberSearch, get) does not exist (join the API team and implement it!)"

I see from other posts that I have to add filter. is this to field or filter and what do I add?

Thanks

Jeremy

**Comment by ebenezer-bendov** [comment]
Okay I have installed content views pro. Where do I get the patch from and where do I put it :)

Thanks

Jeremy

**Comment by ebenezer-bendov** [comment]
okay found the patch. Just need to know what to do with it.

Thanks

**Comment by ebenezer-bendov** [comment]
Progress. I managed to figure out what to do with the patch.  I added the change to admin/views/views.php. 

No drop down with processors appears under the civicrm box in content views

FYI I have set up an API but it does not show on the Manage Data Processors page. Would it normally?

**Comment by agileware-pengyi** [comment]
@ebenezer-bendov Hi Jeremy, thanks for using/testing this plugin.
You mean you create a data processor and add API output? Have you tried the API, like API3 explorer?

Agileware ref: WPCV-29

**Comment by ebenezer-bendov** [comment]
Hi Pengi

Below is the API 3 readout for dataprocessorfield. With all fields. I hope this helps .
Jeremy


{

   "is_error": 0,
   "undefined_fields": [
       "page",
       "noheader"
   ],
   "version": 3,
   "count": 4,
   "values": [
       {
           "id": "30",
           "data_processor_id": "3",
           "weight": "1",
           "name": "contact_id",
           "title": "Contact ID",
           "type": "raw",
           "configuration": {
               "field": "_select__id",
               "datasource": "_select_",
               "is_aggregate": "1"
           }
       },
       {
           "id": "36",
           "data_processor_id": "8",
           "weight": "1",
           "name": "contact_id",
           "title": "Contact ID",
           "type": "raw",
           "configuration": {
               "field": "_select__id",
               "datasource": "_select_",
               "is_aggregate": ""
           }
       },
       {
           "id": "29",
           "data_processor_id": "3",
           "weight": "2",
           "name": "display_name",
           "title": "Display Name",
           "type": "raw",
           "configuration": {
               "field": "_select__display_name",
               "datasource": "_select_",
               "is_aggregate": ""
           }
       },
       {
           "id": "35",
           "data_processor_id": "8",
           "weight": "2",
           "name": "display_name",
           "title": "Display Name",
           "type": "raw",
           "configuration": {
               "field": "_select__display_name",
               "datasource": "_select_",
               "is_aggregate": ""
           }
       }
   ]
}
Access Keys:




________________________________

**Comment by agileware-pengyi** [comment]
@ebenezer-bendov I mean the output defined by each data processor.

Cause you said 
> FYI I have set up an API but it does not show on the Manage Data Processors page. Would it normally?

And you are getting error
> API (MemberSearch, get) does not exist (join the API team and implement it!)

Just want to double-check your setup.

Your output setup should look like this
![output_setup](https://user-images.githubusercontent.com/49378827/75131857-da3d9a00-5728-11ea-9e28-5620b5dda1f1.png)
And after that, you should be able to find this in the API3
![api3](https://user-images.githubusercontent.com/49378827/75131904-0527ee00-5729-11ea-9eac-58d0d44f7d42.png)

Thanks,
Pengyi

**Comment by Bendov56** [comment]
Okay thanks for the pictures. It really helps :) My entity is ebenezerMember. Obviously I have an error. Probably I have not done something I should!

{

    "error_code": "not-found",
    "entity": "EbenezerMember",
    "action": "get",
    "is_error": 1,
    "error_message": "API (EbenezerMember, get) does not exist (join the API team and implement it!)"
}

**Comment by Bendov56** [comment]
FYI I trust what I did with the patch is right?

				);

				$options = apply_filters(PT_CV_PREFIX_ . 'filter_settings_final', $options);
				echo PT_Options_Framework::do_settings( $options, $settings );
				?>
			</div>

**Comment by agileware-pengyi** [comment]
@ebenezer-bendov @Bendov56 yeah, you have the right patch.
By not having the API after you set it up, this is an issue of the Data Processor extension.

The best way is to ask in the extension project. I am not sure if I can help or not, but you can export your data processor configuration and post it here.

**Comment by ebenezer-bendov** [comment]
Thanks for your input. Here is the code. 

{
  "name": "ebenezer_member",
  "title": "Ebenezer Member",
  "type": "default",
  "is_active": "1",
  "configuration": [],
  "storage_configuration": [],
  "data_sources": [
    {
      "weight": "1",
      "name": "_select_",
      "title": "Contact",
      "type": "contact",
      "configuration": {
        "filter": []
      },
      "join_configuration": []
    }
  ],
  "filters": [
    {
      "weight": "1",
      "name": "contact_id",
      "title": "Contact ID",
      "type": "in_api_filter",
      "is_required": "0",
      "is_exposed": "1",
      "configuration": {
        "field": "_select__id",
        "datasource": "_select_",
        "api_entity": "Ebenezer Member",
        "api_action": "Get",
        "value_field": "contact_id",
        "label_field": "contact_id",
        "api_params": ""
      },
      "filter_value": []
    }
  ],
  "fields": [
    {
      "weight": "1",
      "name": "contact_id",
      "title": "Contact ID",
      "type": "raw",
      "configuration": {
        "field": "_select__id",
        "datasource": "_select_",
        "is_aggregate": ""
      }
    },
    {
      "weight": "2",
      "name": "display_name",
      "title": "Display Name",
      "type": "raw",
      "configuration": {
        "field": "_select__display_name",
        "datasource": "_select_",
        "is_aggregate": ""
      }
    }
  ],
  "outputs": [
    {
      "type": "api",
      "configuration": [],
      "permission": "access CiviCRM",
      "api_entity": "Ebenezer Member",
      "api_action": "get",
      "api_count_action": "getcount"
    },
    {
      "type": "contact_search",
      "configuration": {
        "contact_id_field": "contact_id",
        "hidden_fields": [],
        "hide_id_field": "0",
        "help_text": "<p>Contact Search</p>\r\n",
        "expanded_search": "",
        "navigation_parent_path": "Search"
      },
      "permission": "access CiviCRM"
    }
  ]
}

**Comment by Bendov56** [comment]
Can anyone show me what a correct export should look like so I can compare mine with one that works? 
I realise the API does show not under API but under the name I gave it, Ebenezer Membership.

Any help gratefully received :)

**Comment by Bendov56** [comment]
I realise the API is there under the name I gave it, Ebenezer Member

**Comment by Bendov56** [comment]
Hi everyone - this morning I came into the following error. I reinstalled with fresh master but still get the fatal error:

Fatal error: Uncaught Error: Class 'Civi\DataProcessor\Source\CompilerPass\MultipleCustomGroupSource' not found in /home/eboe777/public_html/wp-content/uploads/civicrm/ext/dataprocessor-master/dataprocessor.php:33 Stack trace: #0 /home/eboe777/public_html/wp-content/plugins/civicrm/civicrm/CRM/Utils/Hook.php(286): dataprocessor_civicrm_container(Object(Symfony\Component\DependencyInjection\ContainerBuilder)) #1 /home/eboe777/public_html/wp-content/plugins/civicrm/civicrm/CRM/Utils/Hook/WordPress.php(139): CRM_Utils_Hook->runHooks(Array, 'civicrm_contain...', 1, Object(Symfony\Component\DependencyInjection\ContainerBuilder), NULL, NULL, NULL, NULL, NULL) #2 /home/eboe777/public_html/wp-content/plugins/civicrm/civicrm/CRM/Utils/Hook.php(182): CRM_Utils_Hook_WordPress->invokeViaUF(1, Object(Symfony\Component\DependencyInjection\ContainerBuilder), NULL, NULL, NULL, NULL, NULL, 'civicrm_contain...') #3 /home/eboe777/public_html/wp-content/plugins/civicrm/civicrm/CRM/Utils/Hook.php(2408): CRM_Utils_Hook->invoke(Array, Object(Sy in /home/eboe777/public_html/wp-content/uploads/civicrm/ext/dataprocessor-master/dataprocessor.php on line 33
There has been a critical error on your website. Ple

**Comment by Bendov56** [comment]
okay managed to solve my fatal errors :) Any help on why I am not getting a drop down in content views. Thanks

**Comment by Bendov56** [comment]
Has everything stopped due to Corona or am I now out of the loop? Thanks

**Comment by agileware-justin** [comment]
@Bendov56 sorry, we do not have the resources available at this time to help with this question.
