### ISSUE TITLE
Can't get data displayed

### ISSUE THREAD

**Issue by TheBFGNL** [agileware/content-views-civicrm-data-processor#8]
Hi,

Probably I'm overlooking something, but I created an api entity with the data processor extension with the following result (events titles and id): 

```
    "values": [
        {
            "id": "1",
            "title": "Informatie avond"
        },
        {
            "id": "10",
            "title": "Kinder Disco" 
```

However when I want to create the content view it returns the correct amount of records; however it doesn't display the data.

It might have to do with me being unable to find this setting:
format the title in the display settings -> title content

**Comment by agileware-justin** [comment]
@MatthijsDJ sorry, we do not have the resources available at this time to help with this question.
